### ISSUE TITLE
Drop GM_xmlhttpRequest for /api/graphql when domain count is returned from the API

### ISSUE THREAD

**Issue by double-beep** [userscripters/fire-extra-functionality#4]
Currently, there's an issue open in the metasmoke repo which asks that domain count is returned to methods that return `spam_domains`. Once the feature request is implemented, the script doesn't need to POST `/api/graphql`

**Comment by Oaphi** [comment]
issue [link](https://github.com/Charcoal-SE/metasmoke/issues/867) for future reference

**Comment by double-beep** [comment]
So... turns out that `GM_xmlhttpRequest` wasn't actually needed to query the GraphQL API. I also found out that returning TP/FP/NAA counts for *every* domain on a post would take too much time as there is no way to filter out whitelisted domains (which generally have many metasmoke hits).
